### ISSUE TITLE
Unquoted outputs

### ISSUE THREAD

**Issue by vortexture** [planetscale/create-branch-password-action#1]
Hello, I was so glad to see you had some github actions for planetscale, these make life easier 😁

I had a quick question about the outputs though, would it possible to add some outputs that didn't contain the quotes?

Currently when I try to use `${{ steps.create_password.outputs.username }}` it returns like this `"new_username"`

e.g. in my pipeline if im constructing my connection string on the fly I might do the following
```
"mysql://${{steps.create_password.outputs.username}}:${{ steps.create_password.outputs.password }}@eu-west.connect.psdb.cloud/something?sslaccept=strict"
```
this becomes
```
"mysql://"new_username":"new_password"@eu-west.connect.psdb.cloud/something?sslaccept=strict"
```

I believe this could be achieved by adding -r to your jq command e.g. 
```
username_raw=$(jq -n "$CMDOUT" | jq -r '.username')
```

Thanks!

**Comment by vortexture** [comment]
I threw together a quick example of this, there are probably batter/cleaner ways of doing this though!

https://github.com/DanielPritchard/create-branch-password-action/blob/fix/jq-raw/entrypoint.sh#L11-L13

**Comment by 205g0** [comment]
Did you get this finally working? And, how do you get the password (since it's redacted in the Actions log)?

**Comment by bmorrisondev** [comment]
@DanielPritchard Thanks for reporting this! And apologies for the delay, this slipped passed me. It was brought to my attention just now. I'm looking into this and will get a fix out ASAP.

@205g0 Just reiterating what I stated in https://github.com/planetscale/discussion/discussions/470 for info on this issue. If you wanted to get the password from the logs you'd create another step and echo them out using bash. More details in the first code block of our [announcement post](https://github.com/planetscale/discussion/discussions/470).

**Comment by bmorrisondev** [comment]
@DanielPritchard I just tested the action as is in my test repo and was able to properly get the creds. Can you provide your workflow file so I see what might be going wrong? Mine's at https://github.com/bmorrisondev/test-new-action/blob/main/.github/workflows/password.yml

![CleanShot 2023-05-16 at 09 11 38](https://github.com/planetscale/create-branch-password-action/assets/4684030/002a661b-9eca-465d-a45d-60ff05a2958e)

**Comment by bmorrisondev** [comment]
@DanielPritchard I was able to replicate the issue and test a fix. A PR is open and should be merged in by the end of the day. Thanks again!

https://github.com/planetscale/create-branch-password-action/pull/4

**Comment by vortexture** [comment]
Hello @bmorrisondev, sorry I didn't get back to you there with my actions file, I was focused on other things and missed the github notification!
It looks like #4 would resolve the problem I was facing, thanks!
